### ISSUE TITLE
Vanilla compatible?

### ISSUE THREAD

**Issue by nymphlode** [hifoomin/StageAesthetic#1]
Sorry for posting this here, I didn't see any information about how to contact you otherwise.

Does this mod work with Vanilla people, whether they join me or I join them?

Thanks!

**Comment by hifoomin** [comment]
It's unlikely to work, just tested it as a client and host in public lobbies and experienced either spectating or really high level + gold gain.

**Comment by hifoomin** [comment]
Sorry to misinform you, but yes, it does indeed work client-side as well. Apparently I got super unlucky with online lobbies as I had just tested with a friend and it worked as me being the client.
