### ISSUE TITLE
Moon Variant Too Dark

### ISSUE THREAD

**Issue by myd3boro** [hifoomin/StageAesthetic#2]
![image](https://user-images.githubusercontent.com/42241578/189481797-6fa86759-8ab0-4437-b080-9fd1091884a7.png)

One moon variant is so dark that the tower is barely seen.

**Comment by hifoomin** [comment]
I'll try to fix but can't guarantee anything. It's fog based on distance that controls this and the skybox may be equally distant to the pillar, making it not appear like intended if I try to fix it.
