### ISSUE TITLE
Config has no effect on some variants.

### ISSUE THREAD

**Issue by eGhpGZeMqhlAIRtA1soVFK4JCDnrsxAXjirz97L** [hifoomin/StageAesthetic#5]
S3.Sulfur Pools-Hell Pools and S4.Abyssal Depths-Indigo Depths aren't affected by the config and stay enabled even if turned off.
There may be more variants affected, but these are the ones I've personally noticed.

**Comment by hifoomin** [comment]
Should be fixed in the upcoming update.
