### ISSUE TITLE
Aphelian Sanctuary looked great for me, completely unusable for friends I was playing with

### ISSUE THREAD

**Issue by ShardCollective** [hifoomin/StageAesthetic#7]
So we were doing a run with this mod recently installed, all of our settings are the same and all of our mods are the same (we're using thunderstore's profile sharing feature). When we got to Aphelian Sanctuary in a run, it looked purple/orange-ish for me, but for them it was all a deep foggy blue, and they were unable to see anything at all. Is this a recurring bug, or something that can be fixed? Attached is how it looked for me, I don't have a screenshot for them.
![Risk_of_Rain_2_uiV93Kh87o](https://github.com/hifoomin/StageAesthetic/assets/43937374/e25f5882-0076-42cd-bdf0-4f5e2829ba01)

**Comment by hifoomin** [comment]
First time hearing of this bug, it could be a mod compatbility issue. Can't seem to replicate it, more info would be required. Profile code, host log, client logs and client screenshots if you can.

**Comment by ShardCollective** [comment]
Ok, I'll re-enable the mod when I next play the game and if the issue happens again I'll post logs and stuff. I do think it was this mod though because we had something like 10 mods installed when it happened, and we've been playing with 40+ mods for 2 to 6 hours a day since then, and it hasn't happened again

**Comment by ShardCollective** [comment]
Just a heads up, I re-enabled the mod and did some testing, couldn't replicate the issue, and I doubt I'll be able to test more because unfortunately this seems highly incompatible with Starstorm 2, which we want to play with always. I can make a detailed summary and post logs for all the issues I find with Starstorm 2 if you intend to try to do cross-compatibility with that, otherwise I won't be using StageAesthetic for the time being despite how good it makes the game look.

**Comment by hifoomin** [comment]
That's planned :)
